<?php

function lisa_dev_get_unsafe_query(SelectQuery $query) {
  $args = $query->getArguments();
  foreach ($args as $key => $value) {
    if (!is_numeric($value)) {
      $args[$key] = "'" . $value . "'";
    }
  }
  $args += array(
    '{' => '',
    '}' => ' AS',
  );
  return str_replace(array_keys($args), array_values($args), (string) $query) . PHP_EOL;
}

function lisa_dev_preprocess_html(&$variables) {
  if (module_exists('admin_menu') &&  theme_exists('uottawa_zen_assets')) {
    drupal_add_css(drupal_get_path('module', 'lisa_dev') . '/lisa_dev.admin_menu_fix.less');
  }
}

function theme_exists($theme_name) {
  $themes = list_themes();
  return isset($themes[$theme_name]) && $themes[$theme_name]->status == 1;
}

function lisa_dev_menu_alter(&$menu) {
  if (!module_exists('dual_language_editor')){
    return;
  }
  $info = entity_get_info('node');
  $bundles = array_keys($info['bundles']);
  foreach ($bundles as $bundle) {
    $bundle = str_replace('_', '-', $bundle);
    $menu["node/add/$bundle"]['page callback'] = 'lisa_dev_add_node_goto';
    $menu["node/add/$bundle"]['module'] = 'lisa_dev';
    unset($menu["node/add/$bundle"]['file']);
  }
}

function lisa_dev_add_node_goto($bundle) {
  drupal_goto("entity/node/$bundle/add");
}
